### PR TITLE
I could not sleep

### PR DESCRIPTION
**Pull request by apscandy**

### CODE REVIEW

**Comment by apscandy** [comment]
GG

**Comment by irls-svg** [comment]
i see ur contribution king and i appreciate it:pray: thank u

**Comment by irls-svg** [comment]
finally looking at this but if ur ever bored again and wanna remove the jinja templating + requirements i'm keen to merge this, just wanna keep the script to one file to keep it simple is all

**Comment by apscandy** [comment]
Will do 😃

**Pull request closed without merging**
